'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Loader2, FileText, Download, Eye } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { useRouter } from 'next/navigation';
import { useToast } from '@/components/providers/toast-provider';


interface QuestionnaireSession {
  id: string;
  session_id: string;
  title: string;
  business_idea?: string;
  target_customer?: string;
  problem?: string;
  created_at: string;
  question_count: number;
  stakeholder_count: number;
  has_questionnaire: boolean;
  questionnaire_exported: boolean;
  questionnaire_data?: any;
}

// Helper function to generate comprehensive questionnaire text
const generateComprehensiveQuestionnaireText = (questionnaire: any, title: string): string => {
  let content = `# Research Questionnaire: ${title}\n\n`;
  content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;

  if (questionnaire.timeEstimate) {
    content += `## Time Estimate\n`;
    content += `Total Questions: ${questionnaire.timeEstimate.totalQuestions || 'N/A'}\n`;
    content += `Estimated Duration: ${questionnaire.timeEstimate.estimatedMinutes || 'N/A'}\n\n`;
  }

  // Primary Stakeholders
  if (questionnaire.primaryStakeholders && questionnaire.primaryStakeholders.length > 0) {
    content += `## Primary Stakeholders\n\n`;
    questionnaire.primaryStakeholders.forEach((stakeholder: any, index: number) => {
      content += `### ${index + 1}. ${stakeholder.name}\n`;
      if (stakeholder.description) {
        content += `**Description:** ${stakeholder.description}\n\n`;
      }

      if (stakeholder.questions) {
        if (stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0) {
          content += `**Problem Discovery Questions:**\n`;
          stakeholder.questions.problemDiscovery.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0) {
          content += `**Solution Validation Questions:**\n`;
          stakeholder.questions.solutionValidation.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0) {
          content += `**Follow-up Questions:**\n`;
          stakeholder.questions.followUp.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }
      }
      content += `---\n\n`;
    });
  }

  // Secondary Stakeholders
  if (questionnaire.secondaryStakeholders && questionnaire.secondaryStakeholders.length > 0) {
    content += `## Secondary Stakeholders\n\n`;
    questionnaire.secondaryStakeholders.forEach((stakeholder: any, index: number) => {
      content += `### ${index + 1}. ${stakeholder.name}\n`;
      if (stakeholder.description) {
        content += `**Description:** ${stakeholder.description}\n\n`;
      }

      if (stakeholder.questions) {
        if (stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0) {
          content += `**Problem Discovery Questions:**\n`;
          stakeholder.questions.problemDiscovery.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0) {
          content += `**Solution Validation Questions:**\n`;
          stakeholder.questions.solutionValidation.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0) {
          content += `**Follow-up Questions:**\n`;
          stakeholder.questions.followUp.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }
      }
      content += `---\n\n`;
    });
  }

  content += `\nGenerated by AxWise Customer Research Assistant\nReady for simulation bridge and interview analysis`;
  return content;
};



export default function QuestionnaireHistoryPage(): JSX.Element {
  const router = useRouter();
  const { showToast } = useToast();

  const [questionnaireSessions, setQuestionnaireSessions] = useState<QuestionnaireSession[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<Error | null>(null);
  // Modal state removed - now using full page view

  // Fetch questionnaire history
  const fetchQuestionnaireHistory = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      // Fetch backend sessions
      const response = await fetch('/api/research/sessions');
      let backendSessions: any[] = [];

      if (response.ok) {
        const data = await response.json();
        backendSessions = (Array.isArray(data) ? data : [])
          .filter((session: any) => session.has_questionnaire)
          .map((session: any) => ({
            ...session,
            // Use completed_at as questionnaire generation time for backend sessions
            questionnaire_generated_at: session.completed_at || session.updated_at || session.created_at
          }));
      } else {
        console.warn('Failed to fetch backend sessions:', response.status);
      }

      // Fetch local sessions from localStorage
      let localSessions: any[] = [];
      if (typeof window !== 'undefined') {
        try {
          const { LocalResearchStorage } = await import('@/lib/api/research');
          const allLocalSessions = LocalResearchStorage.getSessions();

          console.log('🔍 All local sessions found:', allLocalSessions.length);
          allLocalSessions.forEach((session, index) => {
            console.log(`Session ${index}:`, {
              session_id: session.session_id,
              business_idea: session.business_idea,
              questions_generated: session.questions_generated,
              message_count: session.messages?.length || 0,
              hasComprehensiveQuestions: session.messages?.some((msg: any) =>
                msg.metadata?.comprehensiveQuestions ||
                (msg.metadata?.type === 'component' && msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT')
              )
            });

            // Debug: Show all messages with metadata for the new session
            if (session.session_id === 'local_1751799349179_kxcl3pb73') {
              console.log(`🔍 DEBUGGING NEW SESSION: ${session.session_id}`);
              if (session.messages) {
                console.log(`Messages for session ${session.session_id}:`, session.messages.length, 'total');
                session.messages.forEach((msg: any, msgIndex: number) => {
                  console.log(`  Message ${msgIndex}:`, {
                    content: msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT' ? 'COMPREHENSIVE_QUESTIONS_COMPONENT' : msg.content?.substring(0, 50) + '...',
                    role: msg.role,
                    hasMetadata: !!msg.metadata,
                    metadataKeys: msg.metadata ? Object.keys(msg.metadata) : [],
                    isQuestionnaireComponent: msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT',
                    fullContent: msg.content?.length > 100 ? msg.content.substring(0, 100) + '...' : msg.content
                  });

                  // Check for comprehensive questions component
                  if (msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT') {
                    console.log(`    ✅ Found COMPREHENSIVE_QUESTIONS_COMPONENT in message ${msgIndex}:`, msg.metadata);
                  }

                  // Check for questions in the API response format
                  if (msg.metadata?.questions) {
                    console.log(`    📋 Found questions in message ${msgIndex}:`, msg.metadata.questions);
                  }

                  // Check for comprehensive questions
                  if (msg.metadata?.comprehensiveQuestions) {
                    console.log(`    🎯 Found comprehensive questions in message ${msgIndex}:`, msg.metadata.comprehensiveQuestions);
                  }
                });
              } else {
                console.log(`❌ No messages found for session ${session.session_id}`);
              }
            }
          });

          // Filter local sessions that have questionnaires (check messages for comprehensive questions)
          localSessions = allLocalSessions
            .filter((session: any) => {
              if (!session.messages || !Array.isArray(session.messages)) return false;

              // Check if any message contains comprehensive questions
              const hasQuestionnaireComponent = session.messages.some((msg: any) =>
                msg.metadata?.comprehensiveQuestions ||
                (msg.metadata?.type === 'component' && msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT')
              );

              // Also check for sessions that have questions_generated but missing component
              const hasQuestionsGenerated = session.questions_generated;

              // Check for questionnaire content in regular messages (legacy format)
              const hasQuestionnaireContent = session.messages.some((msg: any) =>
                msg.role === 'assistant' &&
                msg.content &&
                typeof msg.content === 'string' &&
                (msg.content.includes('Primary Stakeholders') ||
                 msg.content.includes('Secondary Stakeholders') ||
                 msg.content.includes('Problem Discovery Questions') ||
                 msg.content.includes('Solution Validation Questions'))
              );

              return hasQuestionnaireComponent || (hasQuestionsGenerated && hasQuestionnaireContent);
            })
            .map((session: any) => {
              // Extract questionnaire data from messages
              let questionCount = 0;
              let stakeholderCount = 0;

              // First, try to find existing questionnaire component
              let questionnaireMessage = session.messages.find((msg: any) =>
                msg.metadata?.comprehensiveQuestions
              );

              // If no questionnaire component found but session has questions_generated,
              // try to auto-repair by looking for questionnaire content in regular messages
              if (!questionnaireMessage && session.questions_generated) {
                const contentMessage = session.messages.find((msg: any) =>
                  msg.role === 'assistant' &&
                  msg.content &&
                  typeof msg.content === 'string' &&
                  (msg.content.includes('Primary Stakeholders') ||
                   msg.content.includes('Secondary Stakeholders'))
                );

                if (contentMessage) {
                  console.log(`🔧 Auto-repairing session ${session.session_id} - converting content to questionnaire component`);

                  // Create a basic questionnaire structure from the content
                  // This is a fallback - the actual questionnaire might be more complex
                  const basicQuestionnaire = {
                    primaryStakeholders: [
                      {
                        name: "Primary Stakeholder",
                        description: "Stakeholder identified from conversation",
                        questions: {
                          problemDiscovery: ["What challenges do you face?"],
                          solutionValidation: ["Would this solution help?"],
                          followUp: ["Any additional thoughts?"]
                        }
                      }
                    ],
                    secondaryStakeholders: [],
                    timeEstimate: {
                      totalQuestions: 3,
                      estimatedMinutes: 15,
                      primaryQuestions: 3,
                      secondaryQuestions: 0
                    }
                  };

                  // Create questionnaire component message
                  questionnaireMessage = {
                    id: `questionnaire_repair_${Date.now()}`,
                    content: 'COMPREHENSIVE_QUESTIONS_COMPONENT',
                    role: 'assistant',
                    timestamp: new Date().toISOString(),
                    metadata: {
                      type: 'component',
                      comprehensiveQuestions: basicQuestionnaire,
                      businessContext: session.business_idea,
                      autoRepaired: true
                    }
                  };

                  // Add the questionnaire message to the session
                  session.messages.push(questionnaireMessage);

                  // Update the session in localStorage (non-async)
                  try {
                    // Use dynamic import synchronously in browser context
                    if (typeof window !== 'undefined') {
                      import('@/lib/api/research').then(({ LocalResearchStorage }) => {
                        LocalResearchStorage.saveSession(session);
                        console.log(`✅ Auto-repaired session ${session.session_id} saved to localStorage`);
                      }).catch(error => {
                        console.error('Failed to save auto-repaired session:', error);
                      });
                    }
                  } catch (error) {
                    console.error('Failed to import LocalResearchStorage:', error);
                  }
                }
              }

              if (questionnaireMessage?.metadata?.comprehensiveQuestions) {
                const questionnaire = questionnaireMessage.metadata.comprehensiveQuestions;
                const primaryStakeholders = questionnaire.primaryStakeholders || [];
                const secondaryStakeholders = questionnaire.secondaryStakeholders || [];

                stakeholderCount = primaryStakeholders.length + secondaryStakeholders.length;
                questionCount = [...primaryStakeholders, ...secondaryStakeholders].reduce((total: number, stakeholder: any) => {
                  const questions = stakeholder.questions || {};
                  return total +
                    (questions.problemDiscovery?.length || 0) +
                    (questions.solutionValidation?.length || 0) +
                    (questions.followUp?.length || 0);
                }, 0);
              }

              // Try to get the questionnaire generation timestamp
              let questionnaireGeneratedAt = session.created_at;

              if (questionnaireMessage) {
                // Use the questionnaire message timestamp if available
                questionnaireGeneratedAt = questionnaireMessage.timestamp || session.created_at;
              } else if (session.completed_at) {
                // Use session completion time if available
                questionnaireGeneratedAt = session.completed_at;
              } else if (session.updated_at) {
                // Fallback to last update time
                questionnaireGeneratedAt = session.updated_at;
              }

              return {
                id: session.session_id,
                session_id: session.session_id,
                title: session.business_idea || `Local Session ${session.session_id.slice(-8)}`,
                business_idea: session.business_idea,
                target_customer: session.target_customer,
                problem: session.problem,
                created_at: session.created_at,
                questionnaire_generated_at: questionnaireGeneratedAt, // New field for questionnaire generation time
                question_count: questionCount,
                stakeholder_count: stakeholderCount,
                has_questionnaire: true,
                questionnaire_exported: false,
                isLocal: true
              };
            });
        } catch (error) {
          console.error('Error loading local sessions:', error);
        }
      }

      // Combine and deduplicate sessions
      const allSessions = [...backendSessions, ...localSessions];
      const uniqueSessions = allSessions.filter((session, index, self) =>
        index === self.findIndex(s => s.session_id === session.session_id)
      );

      // Sort by questionnaire generation time (newest first)
      uniqueSessions.sort((a, b) => {
        const timeA = (a as any).questionnaire_generated_at || a.created_at;
        const timeB = (b as any).questionnaire_generated_at || b.created_at;
        return new Date(timeB).getTime() - new Date(timeA).getTime();
      });

      setQuestionnaireSessions(uniqueSessions);
    } catch (err) {
      console.error('Error fetching questionnaire history:', err);
      setError(err instanceof Error ? err : new Error('Failed to load questionnaire history'));
      showToast('Failed to load questionnaire history', { variant: 'error' });
    } finally {
      setIsLoading(false);
    }
  }, [showToast]);

  useEffect(() => {
    fetchQuestionnaireHistory();
  }, [fetchQuestionnaireHistory]);

  // Handle using a questionnaire for simulation
  const handleUseForSimulation = useCallback((sessionId: string) => {
    router.push(`/unified-dashboard/research?session=${sessionId}`);
  }, [router]);

  // Modal view removed - now using full page view

  // Handle downloading questionnaire
  const handleDownloadQuestionnaire = useCallback(async (sessionId: string, title: string) => {
    try {
      console.log('📥 Downloading questionnaire for session:', sessionId);

      let questionnaire = null;

      if (sessionId.startsWith('local_')) {
        // Handle local session
        if (typeof window !== 'undefined') {
          const { LocalResearchStorage } = await import('@/lib/api/research');
          const session = LocalResearchStorage.getSession(sessionId);

          if (session?.messages) {
            const questionnaireMessage = session.messages.find((msg: any) =>
              msg.metadata?.comprehensiveQuestions
            );

            if (questionnaireMessage?.metadata?.comprehensiveQuestions) {
              questionnaire = questionnaireMessage.metadata.comprehensiveQuestions;
              console.log('📋 Local questionnaire data for download:', questionnaire);
            }
          }
        }
      } else {
        // Handle backend session
        const response = await fetch(`/api/research/sessions/${sessionId}/questionnaire`);

        if (response.ok) {
          const data = await response.json();
          questionnaire = data.questionnaire;
          console.log('📋 Backend questionnaire data for download:', questionnaire);
        } else {
          const errorText = await response.text();
          console.error('❌ Download failed:', response.status, errorText);
          showToast(`Failed to download questionnaire: ${response.status}`, { variant: 'error' });
          return;
        }
      }

      if (questionnaire) {
        // V3 Enhanced format only - validate structure
        if (!questionnaire.primaryStakeholders && !questionnaire.secondaryStakeholders) {
          throw new Error('Invalid questionnaire format - V3 Enhanced format required');
        }

        // Generate V3 Enhanced format
        const textContent = generateComprehensiveQuestionnaireText(questionnaire, title);

        // Create and download the file
        const blob = new Blob([textContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `questionnaire-${title.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);

        showToast('Questionnaire downloaded successfully', { variant: 'success' });
      } else {
        showToast('No questionnaire data found for this session', { variant: 'error' });
      }
    } catch (error) {
      console.error('❌ Download error:', error);
      showToast('Failed to download questionnaire', { variant: 'error' });
    }
  }, [showToast]);

  // Loading state
  if (isLoading) {
    return (
      <Card className="w-full">
        <CardContent className="flex justify-center items-center py-12">
          <div className="flex flex-col items-center space-y-4">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-muted-foreground">Loading questionnaire history...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Error state
  if (error) {
    return (
      <Alert variant="destructive">
        <AlertTitle>Error Loading Questionnaire History</AlertTitle>
        <AlertDescription>{error.message}</AlertDescription>
      </Alert>
    );
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Generated Questionnaires
        </CardTitle>
        <CardDescription>
          View and use your AI-generated questionnaires for interview simulations
        </CardDescription>
      </CardHeader>

      <CardContent>
        {questionnaireSessions.length > 0 ? (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Questionnaire</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead className="hidden md:table-cell">Questions</TableHead>
                  <TableHead className="hidden md:table-cell">Stakeholders</TableHead>
                  <TableHead className="hidden md:table-cell">Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {questionnaireSessions.map((session) => (
                  <TableRow key={session.id}>
                    <TableCell className="font-medium">
                      <div className="flex items-center gap-2">
                        <FileText className="h-4 w-4 text-muted-foreground" />
                        {session.title || `Questionnaire ${session.id.slice(0, 8)}`}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-col">
                        <span className="text-sm">
                          {new Date((session as any).questionnaire_generated_at || session.created_at).toLocaleDateString('en-GB')}
                        </span>
                        <span className="text-xs text-muted-foreground">
                          {new Date((session as any).questionnaire_generated_at || session.created_at).toLocaleTimeString()}
                        </span>
                      </div>
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <Badge variant="secondary">{session.question_count || 0}</Badge>
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <Badge variant="secondary">{session.stakeholder_count || 0}</Badge>
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <div className="flex gap-1">
                        <Badge variant="default" className="text-xs">
                          Generated
                        </Badge>
                        {session.questionnaire_exported && (
                          <Badge variant="outline" className="text-xs">
                            Exported
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex gap-2 justify-end">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => router.push(`/unified-dashboard/questionnaire-history/${session.session_id}`)}
                          title="View full questionnaire"
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDownloadQuestionnaire(session.session_id, session.title)}
                          title="Download questionnaire"
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleUseForSimulation(session.session_id)}
                        >
                          Use for Simulation
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : (
          <div className="text-center py-8 border rounded-md">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">No questionnaires found.</p>
            <p className="text-sm text-muted-foreground mt-1">
              Use the Research Chat to generate questionnaires for your customer research.
            </p>
            <Button
              className="mt-4"
              onClick={() => router.push('/unified-dashboard/research-chat')}
            >
              Start Research Chat
            </Button>
          </div>
        )}
      </CardContent>

    </Card>
  );
}
