'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Loader2, FileText, ChevronRight, Download, Eye } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { useRouter } from 'next/navigation';
import { useToast } from '@/components/providers/toast-provider';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';

interface QuestionnaireSession {
  id: string;
  session_id: string;
  title: string;
  business_idea?: string;
  target_customer?: string;
  problem?: string;
  created_at: string;
  question_count: number;
  stakeholder_count: number;
  has_questionnaire: boolean;
  questionnaire_exported: boolean;
  questionnaire_data?: any;
}

// Helper function to generate comprehensive questionnaire text
const generateComprehensiveQuestionnaireText = (questionnaire: any, title: string): string => {
  let content = `# Research Questionnaire: ${title}\n\n`;
  content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;

  if (questionnaire.timeEstimate) {
    content += `## Time Estimate\n`;
    content += `Total Questions: ${questionnaire.timeEstimate.totalQuestions || 'N/A'}\n`;
    content += `Estimated Duration: ${questionnaire.timeEstimate.estimatedMinutes || 'N/A'}\n\n`;
  }

  // Primary Stakeholders
  if (questionnaire.primaryStakeholders && questionnaire.primaryStakeholders.length > 0) {
    content += `## Primary Stakeholders\n\n`;
    questionnaire.primaryStakeholders.forEach((stakeholder: any, index: number) => {
      content += `### ${index + 1}. ${stakeholder.name}\n`;
      if (stakeholder.description) {
        content += `**Description:** ${stakeholder.description}\n\n`;
      }

      if (stakeholder.questions) {
        if (stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0) {
          content += `**Problem Discovery Questions:**\n`;
          stakeholder.questions.problemDiscovery.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0) {
          content += `**Solution Validation Questions:**\n`;
          stakeholder.questions.solutionValidation.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0) {
          content += `**Follow-up Questions:**\n`;
          stakeholder.questions.followUp.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }
      }
      content += `---\n\n`;
    });
  }

  // Secondary Stakeholders
  if (questionnaire.secondaryStakeholders && questionnaire.secondaryStakeholders.length > 0) {
    content += `## Secondary Stakeholders\n\n`;
    questionnaire.secondaryStakeholders.forEach((stakeholder: any, index: number) => {
      content += `### ${index + 1}. ${stakeholder.name}\n`;
      if (stakeholder.description) {
        content += `**Description:** ${stakeholder.description}\n\n`;
      }

      if (stakeholder.questions) {
        if (stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0) {
          content += `**Problem Discovery Questions:**\n`;
          stakeholder.questions.problemDiscovery.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0) {
          content += `**Solution Validation Questions:**\n`;
          stakeholder.questions.solutionValidation.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }

        if (stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0) {
          content += `**Follow-up Questions:**\n`;
          stakeholder.questions.followUp.forEach((q: string, qIndex: number) => {
            content += `${qIndex + 1}. ${q}\n`;
          });
          content += `\n`;
        }
      }
      content += `---\n\n`;
    });
  }

  content += `\nGenerated by AxWise Customer Research Assistant\nReady for simulation bridge and interview analysis`;
  return content;
};

// Helper function to generate simple questionnaire text
const generateSimpleQuestionnaireText = (questionnaire: any, title: string): string => {
  let content = `# Research Questionnaire: ${title}\n\n`;
  content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;

  if (questionnaire.problemDiscovery && questionnaire.problemDiscovery.length > 0) {
    content += `## Problem Discovery Questions\n`;
    questionnaire.problemDiscovery.forEach((q: string, index: number) => {
      content += `${index + 1}. ${q}\n`;
    });
    content += `\n`;
  }

  if (questionnaire.solutionValidation && questionnaire.solutionValidation.length > 0) {
    content += `## Solution Validation Questions\n`;
    questionnaire.solutionValidation.forEach((q: string, index: number) => {
      content += `${index + 1}. ${q}\n`;
    });
    content += `\n`;
  }

  if (questionnaire.followUp && questionnaire.followUp.length > 0) {
    content += `## Follow-up Questions\n`;
    questionnaire.followUp.forEach((q: string, index: number) => {
      content += `${index + 1}. ${q}\n`;
    });
    content += `\n`;
  }

  content += `\nGenerated by AxWise Customer Research Assistant\nReady for simulation bridge and interview analysis`;
  return content;
};

export default function QuestionnaireHistoryPage(): JSX.Element {
  const router = useRouter();
  const { showToast } = useToast();

  const [questionnaireSessions, setQuestionnaireSessions] = useState<QuestionnaireSession[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<Error | null>(null);
  const [selectedQuestionnaire, setSelectedQuestionnaire] = useState<any>(null);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState<boolean>(false);

  // Fetch questionnaire history
  const fetchQuestionnaireHistory = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      // Fetch backend sessions
      const response = await fetch('/api/research/sessions');
      let backendSessions: any[] = [];

      if (response.ok) {
        const data = await response.json();
        backendSessions = (Array.isArray(data) ? data : [])
          .filter((session: any) => session.has_questionnaire);
      } else {
        console.warn('Failed to fetch backend sessions:', response.status);
      }

      // Fetch local sessions from localStorage
      let localSessions: any[] = [];
      if (typeof window !== 'undefined') {
        try {
          const { LocalResearchStorage } = await import('@/lib/api/research');
          const allLocalSessions = LocalResearchStorage.getSessions();

          console.log('🔍 All local sessions found:', allLocalSessions.length);
          allLocalSessions.forEach((session, index) => {
            console.log(`Session ${index}:`, {
              session_id: session.session_id,
              business_idea: session.business_idea,
              questions_generated: session.questions_generated,
              message_count: session.messages?.length || 0,
              hasComprehensiveQuestions: session.messages?.some((msg: any) =>
                msg.metadata?.comprehensiveQuestions ||
                (msg.metadata?.type === 'component' && msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT')
              )
            });

            // Debug: Show all messages with metadata for the new session
            if (session.session_id === 'local_1751799349179_kxcl3pb73') {
              console.log(`🔍 DEBUGGING NEW SESSION: ${session.session_id}`);
              if (session.messages) {
                console.log(`Messages for session ${session.session_id}:`, session.messages.length, 'total');
                session.messages.forEach((msg: any, msgIndex: number) => {
                  console.log(`  Message ${msgIndex}:`, {
                    content: msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT' ? 'COMPREHENSIVE_QUESTIONS_COMPONENT' : msg.content?.substring(0, 50) + '...',
                    role: msg.role,
                    hasMetadata: !!msg.metadata,
                    metadataKeys: msg.metadata ? Object.keys(msg.metadata) : [],
                    isQuestionnaireComponent: msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT',
                    fullContent: msg.content?.length > 100 ? msg.content.substring(0, 100) + '...' : msg.content
                  });

                  // Check for comprehensive questions component
                  if (msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT') {
                    console.log(`    ✅ Found COMPREHENSIVE_QUESTIONS_COMPONENT in message ${msgIndex}:`, msg.metadata);
                  }

                  // Check for questions in the API response format
                  if (msg.metadata?.questions) {
                    console.log(`    📋 Found questions in message ${msgIndex}:`, msg.metadata.questions);
                  }

                  // Check for comprehensive questions
                  if (msg.metadata?.comprehensiveQuestions) {
                    console.log(`    🎯 Found comprehensive questions in message ${msgIndex}:`, msg.metadata.comprehensiveQuestions);
                  }
                });
              } else {
                console.log(`❌ No messages found for session ${session.session_id}`);
              }
            }
          });

          // Filter local sessions that have questionnaires (check messages for comprehensive questions)
          localSessions = allLocalSessions
            .filter((session: any) => {
              if (!session.messages || !Array.isArray(session.messages)) return false;

              // Check if any message contains comprehensive questions
              return session.messages.some((msg: any) =>
                msg.metadata?.comprehensiveQuestions ||
                msg.metadata?.type === 'component' && msg.content === 'COMPREHENSIVE_QUESTIONS_COMPONENT'
              );
            })
            .map((session: any) => {
              // Extract questionnaire data from messages
              let questionCount = 0;
              let stakeholderCount = 0;

              const questionnaireMessage = session.messages.find((msg: any) =>
                msg.metadata?.comprehensiveQuestions
              );

              if (questionnaireMessage?.metadata?.comprehensiveQuestions) {
                const questionnaire = questionnaireMessage.metadata.comprehensiveQuestions;
                const primaryStakeholders = questionnaire.primaryStakeholders || [];
                const secondaryStakeholders = questionnaire.secondaryStakeholders || [];

                stakeholderCount = primaryStakeholders.length + secondaryStakeholders.length;
                questionCount = [...primaryStakeholders, ...secondaryStakeholders].reduce((total: number, stakeholder: any) => {
                  const questions = stakeholder.questions || {};
                  return total +
                    (questions.problemDiscovery?.length || 0) +
                    (questions.solutionValidation?.length || 0) +
                    (questions.followUp?.length || 0);
                }, 0);
              }

              return {
                id: session.session_id,
                session_id: session.session_id,
                title: session.business_idea || `Local Session ${session.session_id.slice(-8)}`,
                business_idea: session.business_idea,
                target_customer: session.target_customer,
                problem: session.problem,
                created_at: session.created_at,
                question_count: questionCount,
                stakeholder_count: stakeholderCount,
                has_questionnaire: true,
                questionnaire_exported: false,
                isLocal: true
              };
            });
        } catch (error) {
          console.error('Error loading local sessions:', error);
        }
      }

      // Combine and deduplicate sessions
      const allSessions = [...backendSessions, ...localSessions];
      const uniqueSessions = allSessions.filter((session, index, self) =>
        index === self.findIndex(s => s.session_id === session.session_id)
      );

      // Sort by creation date (newest first)
      uniqueSessions.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

      setQuestionnaireSessions(uniqueSessions);
    } catch (err) {
      console.error('Error fetching questionnaire history:', err);
      setError(err instanceof Error ? err : new Error('Failed to load questionnaire history'));
      showToast('Failed to load questionnaire history', { variant: 'error' });
    } finally {
      setIsLoading(false);
    }
  }, [showToast]);

  useEffect(() => {
    fetchQuestionnaireHistory();
  }, [fetchQuestionnaireHistory]);

  // Handle using a questionnaire for simulation
  const handleUseForSimulation = useCallback((sessionId: string) => {
    router.push(`/unified-dashboard/research?session=${sessionId}`);
  }, [router]);

  // Handle viewing questionnaire
  const handleViewQuestionnaire = useCallback(async (sessionId: string) => {
    try {
      console.log('🔍 Fetching questionnaire for session:', sessionId);

      let questionnaire = null;

      if (sessionId.startsWith('local_')) {
        // Handle local session
        if (typeof window !== 'undefined') {
          const { LocalResearchStorage } = await import('@/lib/api/research');
          const session = LocalResearchStorage.getSession(sessionId);

          if (session?.messages) {
            const questionnaireMessage = session.messages.find((msg: any) =>
              msg.metadata?.comprehensiveQuestions
            );

            if (questionnaireMessage?.metadata?.comprehensiveQuestions) {
              questionnaire = questionnaireMessage.metadata.comprehensiveQuestions;
              console.log('✅ Local questionnaire data loaded:', questionnaire);
            }
          }
        }
      } else {
        // Handle backend session
        const response = await fetch(`/api/research/sessions/${sessionId}/questionnaire`);

        if (response.ok) {
          const data = await response.json();
          questionnaire = data.questionnaire;
          console.log('✅ Backend questionnaire data received:', questionnaire);
        } else {
          const errorText = await response.text();
          console.error('❌ Failed to load questionnaire:', response.status, errorText);
          showToast(`Failed to load questionnaire: ${response.status}`, { variant: 'error' });
          return;
        }
      }

      if (questionnaire) {
        setSelectedQuestionnaire(questionnaire);
        setIsViewDialogOpen(true);
      } else {
        showToast('No questionnaire data found for this session', { variant: 'error' });
      }
    } catch (error) {
      console.error('❌ Error loading questionnaire:', error);
      showToast('Failed to load questionnaire details', { variant: 'error' });
    }
  }, [showToast]);

  // Handle downloading questionnaire
  const handleDownloadQuestionnaire = useCallback(async (sessionId: string, title: string) => {
    try {
      console.log('📥 Downloading questionnaire for session:', sessionId);

      let questionnaire = null;

      if (sessionId.startsWith('local_')) {
        // Handle local session
        if (typeof window !== 'undefined') {
          const { LocalResearchStorage } = await import('@/lib/api/research');
          const session = LocalResearchStorage.getSession(sessionId);

          if (session?.messages) {
            const questionnaireMessage = session.messages.find((msg: any) =>
              msg.metadata?.comprehensiveQuestions
            );

            if (questionnaireMessage?.metadata?.comprehensiveQuestions) {
              questionnaire = questionnaireMessage.metadata.comprehensiveQuestions;
              console.log('📋 Local questionnaire data for download:', questionnaire);
            }
          }
        }
      } else {
        // Handle backend session
        const response = await fetch(`/api/research/sessions/${sessionId}/questionnaire`);

        if (response.ok) {
          const data = await response.json();
          questionnaire = data.questionnaire;
          console.log('📋 Backend questionnaire data for download:', questionnaire);
        } else {
          const errorText = await response.text();
          console.error('❌ Download failed:', response.status, errorText);
          showToast(`Failed to download questionnaire: ${response.status}`, { variant: 'error' });
          return;
        }
      }

      if (questionnaire) {
        // Generate the same format as the chat interface export
        let textContent = '';

        if (questionnaire.primaryStakeholders || questionnaire.secondaryStakeholders) {
          // Use comprehensive format
          textContent = generateComprehensiveQuestionnaireText(questionnaire, title);
        } else {
          // Use simple format
          textContent = generateSimpleQuestionnaireText(questionnaire, title);
        }

        // Create and download the file
        const blob = new Blob([textContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `questionnaire-${title.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);

        showToast('Questionnaire downloaded successfully', { variant: 'success' });
      } else {
        showToast('No questionnaire data found for this session', { variant: 'error' });
      }
    } catch (error) {
      console.error('❌ Download error:', error);
      showToast('Failed to download questionnaire', { variant: 'error' });
    }
  }, [showToast]);

  // Loading state
  if (isLoading) {
    return (
      <Card className="w-full">
        <CardContent className="flex justify-center items-center py-12">
          <div className="flex flex-col items-center space-y-4">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-muted-foreground">Loading questionnaire history...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Error state
  if (error) {
    return (
      <Alert variant="destructive">
        <AlertTitle>Error Loading Questionnaire History</AlertTitle>
        <AlertDescription>{error.message}</AlertDescription>
      </Alert>
    );
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Generated Questionnaires
        </CardTitle>
        <CardDescription>
          View and use your AI-generated questionnaires for interview simulations
        </CardDescription>
      </CardHeader>

      <CardContent>
        {questionnaireSessions.length > 0 ? (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Questionnaire</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="hidden md:table-cell">Questions</TableHead>
                  <TableHead className="hidden md:table-cell">Stakeholders</TableHead>
                  <TableHead className="hidden md:table-cell">Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {questionnaireSessions.map((session) => (
                  <TableRow key={session.id}>
                    <TableCell className="font-medium">
                      <div className="flex items-center gap-2">
                        <FileText className="h-4 w-4 text-muted-foreground" />
                        {session.title || `Questionnaire ${session.id.slice(0, 8)}`}
                      </div>
                    </TableCell>
                    <TableCell>
                      {new Date(session.created_at).toLocaleDateString()}
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <Badge variant="secondary">{session.question_count || 0}</Badge>
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <Badge variant="secondary">{session.stakeholder_count || 0}</Badge>
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <div className="flex gap-1">
                        <Badge variant="default" className="text-xs">
                          Generated
                        </Badge>
                        {session.questionnaire_exported && (
                          <Badge variant="outline" className="text-xs">
                            Exported
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex gap-2 justify-end">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleViewQuestionnaire(session.session_id)}
                          title="View questionnaire"
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDownloadQuestionnaire(session.session_id, session.title)}
                          title="Download questionnaire"
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleUseForSimulation(session.session_id)}
                        >
                          Use for Simulation
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : (
          <div className="text-center py-8 border rounded-md">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">No questionnaires found.</p>
            <p className="text-sm text-muted-foreground mt-1">
              Use the Research Chat to generate questionnaires for your customer research.
            </p>
            <Button
              className="mt-4"
              onClick={() => router.push('/unified-dashboard/research-chat')}
            >
              Start Research Chat
            </Button>
          </div>
        )}
      </CardContent>

      {/* View Questionnaire Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh]">
          <DialogHeader>
            <DialogTitle>Questionnaire Details</DialogTitle>
            <DialogDescription>
              View the generated research questions
            </DialogDescription>
          </DialogHeader>

          <ScrollArea className="max-h-[60vh] pr-4">
            {selectedQuestionnaire && (
              <div className="space-y-6">
                {/* Time Estimate */}
                {selectedQuestionnaire.timeEstimate && (
                  <div className="bg-muted/50 p-4 rounded-lg">
                    <h3 className="font-semibold mb-2">Time Estimate</h3>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <span className="text-muted-foreground">Total Questions:</span>
                        <span className="ml-2 font-medium">{selectedQuestionnaire.timeEstimate.totalQuestions || 'N/A'}</span>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Estimated Duration:</span>
                        <span className="ml-2 font-medium">{selectedQuestionnaire.timeEstimate.estimatedMinutes || 'N/A'}</span>
                      </div>
                    </div>
                  </div>
                )}

                {/* Primary Stakeholders */}
                {selectedQuestionnaire.primaryStakeholders && selectedQuestionnaire.primaryStakeholders.length > 0 && (
                  <div>
                    <h3 className="font-semibold mb-4 text-lg">Primary Stakeholders</h3>
                    <div className="space-y-4">
                      {selectedQuestionnaire.primaryStakeholders.map((stakeholder: any, index: number) => (
                        <div key={index} className="border rounded-lg p-4">
                          <h4 className="font-medium text-base mb-2">{stakeholder.name}</h4>
                          {stakeholder.description && (
                            <p className="text-sm text-muted-foreground mb-3">{stakeholder.description}</p>
                          )}

                          {stakeholder.questions && (
                            <div className="space-y-3">
                              {stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Problem Discovery Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.problemDiscovery.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}

                              {stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Solution Validation Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.solutionValidation.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}

                              {stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Follow-up Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.followUp.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Secondary Stakeholders */}
                {selectedQuestionnaire.secondaryStakeholders && selectedQuestionnaire.secondaryStakeholders.length > 0 && (
                  <div>
                    <h3 className="font-semibold mb-4 text-lg">Secondary Stakeholders</h3>
                    <div className="space-y-4">
                      {selectedQuestionnaire.secondaryStakeholders.map((stakeholder: any, index: number) => (
                        <div key={index} className="border rounded-lg p-4">
                          <h4 className="font-medium text-base mb-2">{stakeholder.name}</h4>
                          {stakeholder.description && (
                            <p className="text-sm text-muted-foreground mb-3">{stakeholder.description}</p>
                          )}

                          {stakeholder.questions && (
                            <div className="space-y-3">
                              {stakeholder.questions.problemDiscovery && stakeholder.questions.problemDiscovery.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Problem Discovery Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.problemDiscovery.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}

                              {stakeholder.questions.solutionValidation && stakeholder.questions.solutionValidation.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Solution Validation Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.solutionValidation.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}

                              {stakeholder.questions.followUp && stakeholder.questions.followUp.length > 0 && (
                                <div>
                                  <h5 className="font-medium text-sm mb-2">Follow-up Questions</h5>
                                  <ul className="list-decimal list-inside space-y-1 text-sm">
                                    {stakeholder.questions.followUp.map((q: string, qIndex: number) => (
                                      <li key={qIndex} className="text-muted-foreground">{q}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Simple format fallback */}
                {(!selectedQuestionnaire.primaryStakeholders && !selectedQuestionnaire.secondaryStakeholders) && (
                  <div className="space-y-4">
                    {selectedQuestionnaire.problemDiscovery && selectedQuestionnaire.problemDiscovery.length > 0 && (
                      <div>
                        <h3 className="font-semibold mb-3">Problem Discovery Questions</h3>
                        <ul className="list-decimal list-inside space-y-2">
                          {selectedQuestionnaire.problemDiscovery.map((q: string, index: number) => (
                            <li key={index} className="text-muted-foreground">{q}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {selectedQuestionnaire.solutionValidation && selectedQuestionnaire.solutionValidation.length > 0 && (
                      <div>
                        <h3 className="font-semibold mb-3">Solution Validation Questions</h3>
                        <ul className="list-decimal list-inside space-y-2">
                          {selectedQuestionnaire.solutionValidation.map((q: string, index: number) => (
                            <li key={index} className="text-muted-foreground">{q}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {selectedQuestionnaire.followUp && selectedQuestionnaire.followUp.length > 0 && (
                      <div>
                        <h3 className="font-semibold mb-3">Follow-up Questions</h3>
                        <ul className="list-decimal list-inside space-y-2">
                          {selectedQuestionnaire.followUp.map((q: string, index: number) => (
                            <li key={index} className="text-muted-foreground">{q}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </ScrollArea>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
