'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { FileText, Target, Users, Lightbulb, CheckCircle, AlertTriangle, RefreshCw, AlertCircle } from 'lucide-react';
import { LoadingSpinner } from '@/components/loading-spinner';
import { generatePRD } from '@/lib/api/prd';
import type { DetailedAnalysisResult, PRDResponse, OperationalPRD, TechnicalPRD } from '@/types/api';

interface PRDDisplayProps {
  analysis: DetailedAnalysisResult;
  prdData?: any | null; // Server-side PRD data
}

export function PRDDisplay({ analysis, prdData: serverPrdData }: PRDDisplayProps) {
  const [prdData, setPrdData] = useState<PRDResponse | null>(serverPrdData);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'operational' | 'technical'>('operational');
  const [autoGenerated, setAutoGenerated] = useState<boolean>(!!serverPrdData);

  // Function to regenerate PRD by refreshing the page with force parameter
  const handleRegenerate = () => {
    if (!analysis?.id) {
      setError('No analysis ID available');
      return;
    }

    setLoading(true);

    // Create URL with force regenerate parameter
    const currentUrl = new URL(window.location.href);
    currentUrl.searchParams.set('regeneratePRD', 'true');

    // Refresh the page to trigger server-side regeneration
    window.location.href = currentUrl.toString();
  };

  // Function for initial generation (fallback for client-side)
  const fetchPRD = async (forceRegenerate: boolean = false) => {
    if (!analysis?.id) {
      console.error('[PRDDisplay] No analysis ID available');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      console.log(`[PRDDisplay] Generating LLM-powered PRD for analysis ID: ${analysis.id}`);
      console.log(`[PRDDisplay] Force regenerate: ${forceRegenerate}`);

      const response = await generatePRD(analysis.id, 'both', forceRegenerate);
      console.log(`[PRDDisplay] Raw API response:`, response);

      if (!response) {
        throw new Error('No response received from PRD API');
      }

      if (!response.success) {
        throw new Error(response.error || 'PRD generation failed');
      }

      if (!response.prd_data) {
        throw new Error('No PRD data in response');
      }

      setPrdData(response);
      setAutoGenerated(true);
      console.log(`[PRDDisplay] Successfully generated PRD with ${response.prd_data.metadata?.generated_from.themes_count || 0} themes, ${response.prd_data.metadata?.generated_from.patterns_count || 0} patterns, ${response.prd_data.metadata?.generated_from.insights_count || 0} insights`);
    } catch (err) {
      console.error('[PRDDisplay] Error generating PRD:', err);
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate PRD. Please try again.';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate PRD when component mounts if analysis is complete and no server data
  useEffect(() => {
    if (analysis?.status === 'completed' && analysis?.id && !prdData && !loading && !autoGenerated && !serverPrdData) {
      console.log('[PRDDisplay] Auto-generating PRD for completed analysis');
      fetchPRD();
    }
  }, [analysis?.status, analysis?.id, prdData, loading, autoGenerated, serverPrdData]);

  // Handle tab change
  const handleTabChange = (value: string) => {
    setActiveTab(value as 'operational' | 'technical');
  };

  // Get priority color class
  const getPriorityColorClass = (priority: string) => {
    switch (priority) {
      case 'High':
        return 'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-300 dark:border-red-800';
      case 'Medium':
        return 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/20 dark:text-amber-300 dark:border-amber-800';
      case 'Low':
        return 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-300 dark:border-green-800';
      default:
        return 'bg-slate-50 text-slate-700 border-slate-200 dark:bg-slate-800/50 dark:text-slate-300 dark:border-slate-700';
    }
  };

  // Render loading state
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <LoadingSpinner size="lg" />
        <p className="mt-4 text-muted-foreground">Generating PRD from analysis results using AI...</p>
        <p className="text-sm text-muted-foreground">This may take a few moments</p>
      </div>
    );
  }

  // Render error state
  if (error) {
    return (
      <Alert variant="destructive" className="mb-6">
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>Error</AlertTitle>
        <AlertDescription>
          {error}
          <Button
            variant="outline"
            size="sm"
            onClick={() => fetchPRD(false)}
            className="ml-2"
          >
            <RefreshCw className="mr-2 h-4 w-4" />
            Try Again
          </Button>
        </AlertDescription>
      </Alert>
    );
  }

  // Render empty state
  if (!prdData) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Product Requirements Document
          </CardTitle>
          <CardDescription>
            Generate an AI-powered PRD based on the analysis results
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-8">
          <p className="text-muted-foreground mb-4">No PRD has been generated yet.</p>
          <Button onClick={() => fetchPRD(false)} disabled={analysis?.status !== 'completed'}>
            <Lightbulb className="mr-2 h-4 w-4" />
            Generate AI-Powered PRD
          </Button>
          {analysis?.status !== 'completed' && (
            <p className="text-sm text-muted-foreground mt-2">
              Analysis must be complete before generating a PRD.
            </p>
          )}
        </CardContent>
      </Card>
    );
  }

  // Determine which tabs to show
  const hasOperationalPRD = !!prdData?.prd_data?.operational_prd;
  const hasTechnicalPRD = !!prdData?.prd_data?.technical_prd;

  console.log('[PRDDisplay] PRD data check:', {
    hasPrdData: !!prdData,
    hasOperationalPRD,
    hasTechnicalPRD,
    prdDataKeys: prdData ? Object.keys(prdData) : [],
    prdDataPrdKeys: prdData?.prd_data ? Object.keys(prdData.prd_data) : []
  });

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Product Requirements Document
            </CardTitle>
            <CardDescription>
              AI-generated PRD from analysis of {prdData.prd_data.metadata?.generated_from.themes_count || 0} themes, {prdData.prd_data.metadata?.generated_from.patterns_count || 0} patterns, and {prdData.prd_data.metadata?.generated_from.insights_count || 0} insights
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex gap-2">
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.themes_count || 0} Themes
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.patterns_count || 0} Patterns
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.insights_count || 0} Insights
              </Badge>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleRegenerate}
              className="flex items-center"
              disabled={loading}
            >
              <RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
              {loading ? 'Regenerating...' : 'Regenerate'}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs
          defaultValue={hasOperationalPRD ? 'operational' : 'technical'}
          value={activeTab}
          onValueChange={handleTabChange}
          className="w-full"
        >
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger
              value="operational"
              disabled={!hasOperationalPRD}
            >
              Operational PRD
            </TabsTrigger>
            <TabsTrigger
              value="technical"
              disabled={!hasTechnicalPRD}
            >
              Technical PRD
            </TabsTrigger>
          </TabsList>

          {/* Operational PRD Content */}
          {hasOperationalPRD && (
            <TabsContent value="operational" className="mt-6">
              <OperationalPRDContent prd={prdData.prd_data.operational_prd!} getPriorityColorClass={getPriorityColorClass} />
            </TabsContent>
          )}

          {/* Technical PRD Content */}
          {hasTechnicalPRD && (
            <TabsContent value="technical" className="mt-6">
              <TechnicalPRDContent prd={prdData.prd_data.technical_prd!} getPriorityColorClass={getPriorityColorClass} />
            </TabsContent>
          )}
        </Tabs>
      </CardContent>
    </Card>
  );
}

// Operational PRD Content Component
function OperationalPRDContent({ prd, getPriorityColorClass }: { prd: OperationalPRD; getPriorityColorClass: (priority: string) => string }) {
  return (
    <div className="space-y-6">
      {/* Objectives */}
      {prd.objectives && prd.objectives.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Target className="h-5 w-5" />
            Objectives
          </h3>
          <div className="space-y-3">
            {prd.objectives.map((objective, index) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-2">{objective.title}</h4>
                <p className="text-sm text-muted-foreground">{objective.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Scope */}
      {prd.scope && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Scope</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.scope.included && prd.scope.included.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-green-700 dark:text-green-300">
                  <CheckCircle className="h-4 w-4" />
                  Included
                </h4>
                <ul className="space-y-1">
                  {prd.scope.included.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
            {prd.scope.excluded && prd.scope.excluded.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-red-700 dark:text-red-300">
                  <AlertTriangle className="h-4 w-4" />
                  Excluded
                </h4>
                <ul className="space-y-1">
                  {prd.scope.excluded.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* User Stories */}
      {prd.user_stories && prd.user_stories.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Users className="h-5 w-5" />
            User Stories
          </h3>
          <Accordion type="single" collapsible className="w-full">
            {prd.user_stories.map((story, index) => (
              <AccordionItem key={index} value={`story-${index}`}>
                <AccordionTrigger className="text-left">
                  {story.story}
                </AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-3">
                    {story.acceptance_criteria && story.acceptance_criteria.length > 0 && (
                      <div>
                        <h5 className="font-medium mb-1">Acceptance Criteria:</h5>
                        <ul className="space-y-1">
                          {story.acceptance_criteria.map((criteria, i) => (
                            <li key={i} className="text-sm text-muted-foreground">• {criteria}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    <div className="grid md:grid-cols-3 gap-3 text-sm">
                      {story.what && (
                        <div>
                          <span className="font-medium">What:</span> {story.what}
                        </div>
                      )}
                      {story.why && (
                        <div>
                          <span className="font-medium">Why:</span> {story.why}
                        </div>
                      )}
                      {story.how && (
                        <div>
                          <span className="font-medium">How:</span> {story.how}
                        </div>
                      )}
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      )}

      {/* Requirements */}
      {prd.requirements && prd.requirements.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Requirements</h3>
          <div className="space-y-3">
            {prd.requirements.map((req, index) => (
              <div key={index} className={`border rounded-lg p-4 ${getPriorityColorClass(req.priority)}`}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono text-sm">{req.id}</span>
                  <Badge variant="outline" className="bg-white dark:bg-slate-800 dark:border-slate-700">
                    {req.priority} Priority
                  </Badge>
                </div>
                <h4 className="font-medium mb-2">{req.title}</h4>
                <p className="text-sm text-muted-foreground">{req.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Success Metrics */}
      {prd.success_metrics && prd.success_metrics.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Lightbulb className="h-5 w-5" />
            Success Metrics
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.success_metrics.map((metric, index) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-1">{metric.metric}</h4>
                <p className="text-sm font-medium text-green-700 dark:text-green-300 mb-2">{metric.target}</p>
                <p className="text-xs text-muted-foreground">{metric.measurement_method}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// Technical PRD Content Component
function TechnicalPRDContent({ prd, getPriorityColorClass }: { prd: TechnicalPRD; getPriorityColorClass: (priority: string) => string }) {
  return (
    <div className="space-y-6">
      {/* Objectives */}
      {prd.objectives && prd.objectives.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Target className="h-5 w-5" />
            Technical Objectives
          </h3>
          <div className="space-y-3">
            {prd.objectives.map((objective, index) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-2">{objective.title}</h4>
                <p className="text-sm text-muted-foreground">{objective.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Scope */}
      {prd.scope && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Technical Scope</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.scope.included && prd.scope.included.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-green-700 dark:text-green-300">
                  <CheckCircle className="h-4 w-4" />
                  Included Components
                </h4>
                <ul className="space-y-1">
                  {prd.scope.included.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
            {prd.scope.excluded && prd.scope.excluded.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-red-700 dark:text-red-300">
                  <AlertTriangle className="h-4 w-4" />
                  Excluded Components
                </h4>
                <ul className="space-y-1">
                  {prd.scope.excluded.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Architecture */}
      {prd.architecture && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <FileText className="h-5 w-5" />
            System Architecture
          </h3>
          {prd.architecture.overview && (
            <div className="border rounded-lg p-4 mb-4 bg-muted/30 dark:bg-slate-800/50">
              <h4 className="font-medium mb-2">Architecture Overview</h4>
              <p className="text-sm text-muted-foreground">{prd.architecture.overview}</p>
            </div>
          )}

          {prd.architecture.components && prd.architecture.components.length > 0 && (
            <div>
              <h4 className="font-medium mb-3">System Components</h4>
              <div className="space-y-3">
                {prd.architecture.components.map((component, index) => (
                  <div key={index} className="border rounded-lg p-4">
                    <h5 className="font-medium mb-2">{component.name}</h5>
                    <p className="text-sm text-muted-foreground mb-2">{component.purpose}</p>
                    {component.interactions && component.interactions.length > 0 && (
                      <div>
                        <span className="text-xs font-medium text-muted-foreground">Interactions:</span>
                        <ul className="text-xs text-muted-foreground mt-1">
                          {component.interactions.map((interaction, i) => (
                            <li key={i}>• {interaction}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {prd.architecture.data_flow && (
            <div className="border rounded-lg p-4 mt-4 bg-muted/30 dark:bg-slate-800/50">
              <h4 className="font-medium mb-2">Data Flow</h4>
              <p className="text-sm text-muted-foreground">{prd.architecture.data_flow}</p>
            </div>
          )}
        </div>
      )}

      {/* Implementation Requirements */}
      {prd.implementation_requirements && prd.implementation_requirements.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Implementation Requirements</h3>
          <div className="space-y-3">
            {prd.implementation_requirements.map((req, index) => (
              <div key={index} className={`border rounded-lg p-4 ${getPriorityColorClass(req.priority)}`}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono text-sm">{req.id}</span>
                  <Badge variant="outline" className="bg-white dark:bg-slate-800 dark:border-slate-700">
                    {req.priority} Priority
                  </Badge>
                </div>
                <h4 className="font-medium mb-2">{req.title}</h4>
                <p className="text-sm text-muted-foreground mb-2">{req.description}</p>
                {req.dependencies && req.dependencies.length > 0 && (
                  <div>
                    <span className="text-xs font-medium text-muted-foreground">Dependencies:</span>
                    <div className="flex flex-wrap gap-1 mt-1">
                      {req.dependencies.map((dep, i) => (
                        <Badge key={i} variant="secondary" className="text-xs">{dep}</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Testing & Validation */}
      {prd.testing_validation && prd.testing_validation.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Testing & Validation</h3>
          <div className="space-y-3">
            {prd.testing_validation.map((test, index) => (
              <div key={index} className="border rounded-lg p-4">
                <h4 className="font-medium mb-2">{test.test_type}</h4>
                <p className="text-sm text-muted-foreground mb-2">{test.description}</p>
                <div className="bg-muted/30 dark:bg-slate-800/50 rounded p-2">
                  <span className="text-xs font-medium">Success Criteria:</span>
                  <p className="text-xs text-muted-foreground mt-1">{test.success_criteria}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Technical Success Metrics */}
      {prd.success_metrics && prd.success_metrics.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Lightbulb className="h-5 w-5" />
            Technical Success Metrics
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.success_metrics.map((metric, index) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-1">{metric.metric}</h4>
                <p className="text-sm font-medium text-green-700 dark:text-green-300 mb-2">{metric.target}</p>
                <p className="text-xs text-muted-foreground">{metric.measurement_method}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default PRDDisplay;
