'use client';

import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { FileText, Target, Users, Lightbulb, CheckCircle, AlertTriangle, RefreshCw, AlertCircle } from 'lucide-react';
import { LoadingSpinner } from '@/components/loading-spinner';
import { generatePRD } from '@/lib/api/prd';
import type { DetailedAnalysisResult, PRDResponse, OperationalPRD, TechnicalPRD } from '@/types/api';
import { JiraExportButton } from './JiraExportButton';

import { useSearchParams } from 'next/navigation';

interface PRDDisplayProps {
  analysis: DetailedAnalysisResult;
  prdData?: any | null; // Server-side PRD data
}

export function PRDDisplay({ analysis, prdData: serverPrdData }: PRDDisplayProps) {
  const [prdData, setPrdData] = useState<PRDResponse | null>(serverPrdData);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'operational' | 'technical'>('operational');
  const [autoGenerated, setAutoGenerated] = useState<boolean>(!!serverPrdData);


  // Prevent duplicate fetches when forcing regeneration
  const forceTriggeredRef = useRef(false);

  // Regenerate PRD without full page reload; also mark URL temporarily
  const handleRegenerate = () => {
    if (!analysis?.id) {
      setError('No analysis ID available');
      return;
    }

    setLoading(true);

    // Trigger regeneration directly
    forceTriggeredRef.current = true;
    void fetchPRD(true);

    // Optionally add a timestamp to the URL as a visual indicator (then we clean it up)
    try {
      const url = new URL(window.location.href);
      url.searchParams.set('timestamp', Date.now().toString());
      window.history.replaceState({}, '', url.toString());
    } catch { }
  };

  // Function for initial generation (fallback for client-side)
  const fetchPRD = async (forceRegenerate: boolean = false) => {
    if (!analysis?.id) {
      console.error('[PRDDisplay] No analysis ID available');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      console.log(`[PRDDisplay] Generating LLM-powered PRD for analysis ID: ${analysis.id}`);
      console.log(`[PRDDisplay] Force regenerate: ${forceRegenerate}`);

      const response = await generatePRD(analysis.id, 'both', forceRegenerate);
      console.log(`[PRDDisplay] Raw API response:`, response);

      if (!response) {
        throw new Error('No response received from PRD API');
      }

      if (!response.success) {
        throw new Error(response.error || 'PRD generation failed');
      }

      if (!response.prd_data) {
        throw new Error('No PRD data in response');
      }

      setPrdData(response);
      setAutoGenerated(true);
      console.log(`[PRDDisplay] Successfully generated PRD with ${response.prd_data.metadata?.generated_from.themes_count || 0} themes, ${response.prd_data.metadata?.generated_from.patterns_count || 0} patterns, ${response.prd_data.metadata?.generated_from.insights_count || 0} insights`);
    } catch (err) {
      console.error('[PRDDisplay] Error generating PRD:', err);
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate PRD. Please try again.';
      setError(errorMessage);

    } finally {
      setLoading(false);
    }
  };

  // Auto-generate PRD when component mounts if analysis is complete and no server data
  useEffect(() => {
    if (analysis?.status === 'completed' && analysis?.id && !prdData && !loading && !autoGenerated && !serverPrdData && !forceTriggeredRef.current) {
      console.log('[PRDDisplay] Auto-generating PRD for completed analysis');
      fetchPRD();
    }
  }, [analysis?.status, analysis?.id, prdData, loading, autoGenerated, serverPrdData]);

  // Handle tab change
  const handleTabChange = (value: string) => {
    setActiveTab(value as 'operational' | 'technical');
  };

  // Get priority color class
  const getPriorityColorClass = (priority: string) => {
    switch (priority) {

      case 'High':
        return 'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-300 dark:border-red-800';
      case 'Medium':
        return 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/20 dark:text-amber-300 dark:border-amber-800';
      case 'Low':
        return 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-300 dark:border-green-800';
      default:
        return 'bg-slate-50 text-slate-700 border-slate-200 dark:bg-slate-800/50 dark:text-slate-300 dark:border-slate-700';
    }
  };

  // Detect URL triggers for forced regeneration (regeneratePRD or timestamp)
  const searchParams = useSearchParams();
  useEffect(() => {
    const regenerateFlag = searchParams.get('regeneratePRD') === 'true';
    const hasTimestamp = searchParams.has('timestamp');
    if ((regenerateFlag || hasTimestamp) && analysis?.status === 'completed' && analysis?.id) {
      // Avoid duplicate force calls
      if (forceTriggeredRef.current) return;
      forceTriggeredRef.current = true;

      // Force regeneration once, then clean the URL to avoid loops
      void fetchPRD(true);
      try {
        const url = new URL(window.location.href);
        url.searchParams.delete('regeneratePRD');
        url.searchParams.delete('timestamp');
        window.history.replaceState({}, '', url.toString());
      } catch { }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams, analysis?.status, analysis?.id]);

  // Render loading state
  if (loading) {

    return (
      <div className="flex flex-col items-center justify-center py-12">
        <LoadingSpinner size="lg" />
        <p className="mt-4 text-muted-foreground">Generating PRD from analysis results using AI...</p>
        <p className="text-sm text-muted-foreground">This may take a few moments</p>
      </div>
    );
  }

  // Render error state
  if (error) {
    return (
      <Alert variant="destructive" className="mb-6">
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>Error</AlertTitle>
        <AlertDescription>
          {error}
          <Button
            variant="outline"
            size="sm"
            onClick={() => fetchPRD(false)}
            className="ml-2"
          >
            <RefreshCw className="mr-2 h-4 w-4" />
            Try Again
          </Button>
        </AlertDescription>
      </Alert>
    );
  }

  // Render empty state
  if (!prdData) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Product Requirements Document
          </CardTitle>
          <CardDescription>
            Generate an AI-powered PRD based on the analysis results
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-8">
          <p className="text-muted-foreground mb-4">No PRD has been generated yet.</p>
          <Button onClick={() => fetchPRD(false)} disabled={analysis?.status !== 'completed'}>
            <Lightbulb className="mr-2 h-4 w-4" />
            Generate AI-Powered PRD
          </Button>
          {analysis?.status !== 'completed' && (
            <p className="text-sm text-muted-foreground mt-2">
              Analysis must be complete before generating a PRD.
            </p>
          )}
        </CardContent>
      </Card>
    );
  }

  // Determine which tabs to show
  const hasOperationalPRD = !!prdData?.prd_data?.operational_prd;
  const hasTechnicalPRD = !!prdData?.prd_data?.technical_prd;

  console.log('[PRDDisplay] PRD data check:', {
    hasPrdData: !!prdData,
    hasOperationalPRD,
    hasTechnicalPRD,
    prdDataKeys: prdData ? Object.keys(prdData) : [],
    prdDataPrdKeys: prdData?.prd_data ? Object.keys(prdData.prd_data) : []
  });

  return (
    <Card className="bg-white/40 dark:bg-slate-950/40 backdrop-blur-sm border-border/50">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2 text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">
              <FileText className="h-5 w-5 text-foreground" />
              Product Requirements Document
            </CardTitle>
            <CardDescription>
              AI-generated PRD from analysis of {prdData.prd_data.metadata?.generated_from.themes_count || 0} themes, {prdData.prd_data.metadata?.generated_from.patterns_count || 0} patterns, {prdData.prd_data.metadata?.generated_from.insights_count || 0} insights, and {prdData.prd_data.metadata?.generated_from.personas_count || 0} personas
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex gap-2">
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.themes_count || 0} Themes
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.patterns_count || 0} Patterns
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.prd_data.metadata?.generated_from.insights_count || 0} Insights
              </Badge>
              <Badge variant="outline" className="bg-purple-500/10 text-purple-700 dark:text-purple-300">
                {prdData.prd_data.metadata?.generated_from.personas_count || 0} Personas
              </Badge>
            </div>
            <div className="flex gap-2">
              <JiraExportButton analysisId={analysis.id.toString()} disabled={loading} />
              <Button
                variant="outline"
                size="sm"
                onClick={handleRegenerate}
                className="flex items-center"
                disabled={loading}
              >
                <RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
                {loading ? 'Regenerating...' : 'Regenerate'}
              </Button>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs
          defaultValue={hasOperationalPRD ? 'operational' : 'technical'}
          value={activeTab}
          onValueChange={handleTabChange}
          className="w-full"
        >
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger
              value="operational"
              disabled={!hasOperationalPRD}
            >
              Operational PRD
            </TabsTrigger>
            <TabsTrigger
              value="technical"
              disabled={!hasTechnicalPRD}
            >
              Technical PRD
            </TabsTrigger>
          </TabsList>

          {/* Operational PRD Content */}
          {hasOperationalPRD && (
            <TabsContent value="operational" className="mt-6">
              <OperationalPRDContent prd={prdData.prd_data.operational_prd!} getPriorityColorClass={getPriorityColorClass} />
            </TabsContent>
          )}

          {/* Technical PRD Content */}
          {hasTechnicalPRD && (
            <TabsContent value="technical" className="mt-6">
              <TechnicalPRDContent prd={prdData.prd_data.technical_prd!} getPriorityColorClass={getPriorityColorClass} />
            </TabsContent>
          )}
        </Tabs>
      </CardContent>
    </Card>
  );
}

// Operational PRD Content Component
function OperationalPRDContent({ prd, getPriorityColorClass }: { prd: OperationalPRD; getPriorityColorClass: (priority: string) => string }) {
  // Prefer new BRD/Implementation Blueprint when present; fallback to legacy shape
  const brd: any = (prd as any).brd;
  const impl: any = (prd as any).implementation_blueprint ?? (prd as any).implementationBlueprint;

  const objectives = (brd?.objectives ?? prd.objectives) || [];
  const scope = brd?.scope ?? prd.scope;

  // User stories: use only prd.user_stories (ignore stakeholder_scenarios for display)
  const userStories: any[] = (prd as any).user_stories || [];
  // Try to enrich user stories with justification from BRD stakeholder_scenarios when missing
  const stakeholderScenarios: any[] | undefined = brd?.stakeholder_scenarios;
  const enrichedUserStories: any[] = (userStories || []).map((s: any, i: number) => {
    const scenario = stakeholderScenarios && stakeholderScenarios.length === (userStories || []).length
      ? stakeholderScenarios[i]
      : undefined;
    const justification = s?.justification ?? scenario?.justification;
    const acceptance_criteria = Array.isArray(s?.acceptance_criteria) && s.acceptance_criteria.length > 0
      ? s.acceptance_criteria
      : (Array.isArray(scenario?.acceptance_criteria) ? scenario!.acceptance_criteria : undefined);
    return { ...s, ...(justification ? { justification } : {}), ...(acceptance_criteria ? { acceptance_criteria } : {}) };
  });


  // For specifications: prefer core_specifications; fallback to requirements
  const coreSpecifications: any[] | undefined = brd?.core_specifications;
  const legacyRequirements = (!coreSpecifications || coreSpecifications.length === 0) ? (prd as any).requirements : [];

  const successMetrics = (brd?.success_metrics ?? prd.success_metrics) || [];

  return (
    <div className="space-y-6">
      {/* Objectives */}
      {objectives.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Target className="h-5 w-5" />
            Objectives
          </h3>
          <div className="space-y-3">
            {objectives.map((objective: any, index: number) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-2">{objective.title}</h4>
                <p className="text-sm text-muted-foreground">{objective.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Scope */}
      {scope && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Scope</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {scope.included && scope.included.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-green-700 dark:text-green-300">
                  <CheckCircle className="h-4 w-4" />
                  Included
                </h4>
                <ul className="space-y-1">
                  {scope.included.map((item: string, index: number) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
            {scope.excluded && scope.excluded.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-red-700 dark:text-red-300">
                  <AlertTriangle className="h-4 w-4" />
                  Excluded
                </h4>
                <ul className="space-y-1">
                  {scope.excluded.map((item: string, index: number) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Stakeholder Scenarios (primary user stories from BRD) */}
      {stakeholderScenarios && stakeholderScenarios.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Users className="h-5 w-5" />
            Stakeholder Scenarios
          </h3>
          <Accordion type="single" collapsible className="w-full">
            {stakeholderScenarios.map((scenario: any, index: number) => (
              <AccordionItem key={index} value={`scenario-${index}`}>
                <AccordionTrigger className="text-left">
                  {scenario.scenario}
                </AccordionTrigger>
                <AccordionContent>
                  {/* What / Why / How */}
                  {(scenario.what || scenario.why || scenario.how) && (
                    <div className="grid md:grid-cols-3 gap-3 text-sm pb-3">
                      <div>
                        <span className="font-medium">What:</span> {scenario.what || '—'}
                      </div>
                      <div>
                        <span className="font-medium">Why:</span> {scenario.why || '—'}
                      </div>
                      <div>
                        <span className="font-medium">How:</span> {scenario.how || '—'}
                      </div>
                    </div>
                  )}

                  {Array.isArray(scenario.acceptance_criteria) && scenario.acceptance_criteria.length > 0 && (
                    <div className="pt-1 pb-3">
                      <h4 className="font-medium mb-1">Acceptance Criteria</h4>
                      <ul className="list-disc pl-5 space-y-1">
                        {scenario.acceptance_criteria.map((ac: string, idx: number) => (
                          <li key={idx} className="text-sm text-muted-foreground">{ac}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {scenario.justification && (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2 border-t">
                      <div>
                        <h4 className="font-medium mb-1 mt-2">Linked Theme</h4>
                        <p className="text-sm text-muted-foreground">{scenario.justification.linked_theme}</p>
                      </div>
                      <div>
                        <h4 className="font-medium mb-1 mt-2">Impact</h4>
                        <Badge variant="outline" className={getPriorityColorClass(scenario.justification.impact_score)}>
                          {scenario.justification.impact_score}
                        </Badge>
                        {scenario.justification.frequency && (
                          <span className="ml-2 text-xs text-muted-foreground">
                            Frequency: {typeof scenario.justification.frequency === 'number'
                              ? (scenario.justification.frequency * 100).toFixed(0) + '%'
                              : scenario.justification.frequency}
                          </span>
                        )}
                      </div>
                      <div>
                        <h4 className="font-medium mb-1 mt-2">Evidence</h4>
                        <ul className="list-disc pl-5 space-y-1">
                          {(scenario.justification.evidence_quotes || []).map((q: string, qi: number) => (
                            <li key={qi} className="text-sm text-muted-foreground italic">&quot;{q}&quot;</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      )}

      {/* User Stories (summary - shown if no stakeholder scenarios or as supplement) */}
      {enrichedUserStories && enrichedUserStories.length > 0 && (!stakeholderScenarios || stakeholderScenarios.length === 0) && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Users className="h-5 w-5" />
            User Stories
          </h3>
          <Accordion type="single" collapsible className="w-full">
            {enrichedUserStories.map((story: any, index: number) => (
              <AccordionItem key={index} value={`story-${index}`}>
                <AccordionTrigger className="text-left">
                  {story.story}
                </AccordionTrigger>
                <AccordionContent>
                  <div className="grid md:grid-cols-3 gap-3 text-sm">
                    <div>
                      <span className="font-medium">What:</span> {story.what || '—'}
                    </div>
                    <div>
                      <span className="font-medium">Why:</span> {story.why || '—'}
                    </div>
                    <div>
                      <span className="font-medium">How:</span> {story.how || '—'}
                    </div>
                  </div>
                  {Array.isArray(story.acceptance_criteria) && story.acceptance_criteria.length > 0 && (
                    <div className="pt-3">
                      <h4 className="font-medium mb-1">Acceptance Criteria</h4>
                      <ul className="list-disc pl-5 space-y-1">
                        {story.acceptance_criteria.map((ac: string, idx: number) => (
                          <li key={idx} className="text-sm text-muted-foreground">{ac}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {story.justification && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-3">
                      <div>
                        <h4 className="font-medium mb-1">Linked Theme</h4>
                        <p className="text-sm text-muted-foreground">{story.justification.linked_theme}</p>
                      </div>
                      <div>
                        <h4 className="font-medium mb-1">Evidence</h4>
                        <ul className="list-disc pl-5 space-y-1">
                          {(story.justification.evidence_quotes || []).map((q: string, qi: number) => (
                            <li key={qi} className="text-sm text-muted-foreground">{q}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      )}

      {/* Core Specifications (new) or Requirements (legacy) */}
      {coreSpecifications && coreSpecifications.length > 0 ? (
        <div>
          <h3 className="text-lg font-semibold mb-3">Core Specifications</h3>
          <Accordion type="multiple" className="space-y-2">
            {coreSpecifications.map((spec: any, index: number) => (
              <AccordionItem key={index} value={`spec-${index}`} className="border rounded-md">
                <AccordionTrigger className="px-4 py-2 hover:no-underline">
                  <div className="flex items-center justify-between w-full">
                    <span className="text-left">
                      <span className="font-medium">{spec.id}:</span> {spec.specification}
                    </span>
                    <Badge variant="outline">{spec.priority}</Badge>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="px-4 pb-3">
                  {spec.weighting && (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-3">
                      <div>
                        <h4 className="font-medium mb-2">Impact Score</h4>
                        <p className="text-sm">{spec.weighting.impact_score}</p>
                      </div>
                      <div>
                        <h4 className="font-medium mb-2">Frequency</h4>
                        <p className="text-sm">{typeof spec.weighting.frequency === 'number' ? spec.weighting.frequency.toFixed(2) : spec.weighting.frequency}</p>
                      </div>
                      <div>
                        <h4 className="font-medium mb-2">Basis</h4>
                        <p className="text-sm">{spec.weighting.priority_basis}</p>
                      </div>
                    </div>
                  )}
                  {spec.related_scenarios && spec.related_scenarios.length > 0 && (
                    <div>
                      <h4 className="font-medium mb-1">Related Scenarios</h4>
                      <div className="flex flex-wrap gap-1">
                        {spec.related_scenarios.map((sid: string, idx: number) => (
                          <Badge key={idx} variant="outline">{sid}</Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      ) : (
        legacyRequirements && legacyRequirements.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-3">Requirements</h3>
            <Accordion type="multiple" className="space-y-2">
              {legacyRequirements.map((req: any, index: number) => (
                <AccordionItem key={index} value={`req-${index}`} className="border rounded-md">
                  <AccordionTrigger className="px-4 py-2 hover:no-underline">
                    <div className="flex items-center justify-between w-full">
                      <span className="text-left">
                        <span className="font-medium">{req.id}:</span> {req.title}
                      </span>
                      <Badge variant="outline">{req.priority}</Badge>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="px-4 pb-3">
                    <p className="mb-3">{req.description}</p>
                    {req.related_user_stories && req.related_user_stories.length > 0 && (
                      <div>
                        <h4 className="font-medium mb-1">Related User Stories</h4>
                        <div className="flex flex-wrap gap-1">
                          {req.related_user_stories.map((storyId: string, idx: number) => (
                            <Badge key={idx} variant="outline">{storyId}</Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        )
      )}

      {/* Success Metrics - prefer BRD metrics which are richer */}
      {successMetrics && successMetrics.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Lightbulb className="h-5 w-5" />
            Success Metrics
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {successMetrics.map((metric: any, index: number) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-1">{metric.metric}</h4>
                <p className="text-sm font-medium text-green-700 dark:text-green-300 mb-2">{metric.target}</p>
                <p className="text-xs text-muted-foreground">{metric.measurement_method}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// Technical PRD Content Component
function TechnicalPRDContent({ prd, getPriorityColorClass }: { prd: TechnicalPRD; getPriorityColorClass: (priority: string) => string }) {
  return (
    <div className="space-y-6">
      {/* Objectives */}
      {prd.objectives && prd.objectives.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Target className="h-5 w-5" />
            Technical Objectives

          </h3>
          <div className="space-y-3">
            {prd.objectives.map((objective, index) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-2">{objective.title}</h4>
                <p className="text-sm text-muted-foreground">{objective.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Scope */}
      {prd.scope && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Technical Scope</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.scope.included && prd.scope.included.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-green-700 dark:text-green-300">
                  <CheckCircle className="h-4 w-4" />
                  Included Components
                </h4>
                <ul className="space-y-1">
                  {prd.scope.included.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
            {prd.scope.excluded && prd.scope.excluded.length > 0 && (
              <div className="border rounded-lg p-4">
                <h4 className="font-medium mb-2 flex items-center gap-2 text-red-700 dark:text-red-300">
                  <AlertTriangle className="h-4 w-4" />
                  Excluded Components
                </h4>
                <ul className="space-y-1">
                  {prd.scope.excluded.map((item, index) => (
                    <li key={index} className="text-sm text-muted-foreground">• {item}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Architecture */}
      {prd.architecture && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <FileText className="h-5 w-5" />
            System Architecture
          </h3>
          {prd.architecture.overview && (
            <div className="border rounded-lg p-4 mb-4 bg-muted/30 dark:bg-slate-800/50">
              <h4 className="font-medium mb-2">Architecture Overview</h4>
              <p className="text-sm text-muted-foreground">{prd.architecture.overview}</p>
            </div>
          )}

          {prd.architecture.components && prd.architecture.components.length > 0 && (
            <div>
              <h4 className="font-medium mb-3">System Components</h4>
              <div className="space-y-3">
                {prd.architecture.components.map((component, index) => (
                  <div key={index} className="border rounded-lg p-4">
                    <h5 className="font-medium mb-2">{component.name}</h5>
                    <p className="text-sm text-muted-foreground mb-2">{component.purpose}</p>
                    {(component as { technology_stack?: string }).technology_stack && (
                      <div className="mb-2">
                        <span className="text-xs font-medium text-blue-600 dark:text-blue-400">Tech Stack: </span>
                        <span className="text-xs text-muted-foreground">{(component as { technology_stack?: string }).technology_stack}</span>
                      </div>
                    )}
                    {component.interactions && component.interactions.length > 0 && (
                      <div>
                        <span className="text-xs font-medium text-muted-foreground">Interactions:</span>
                        <ul className="text-xs text-muted-foreground mt-1">
                          {component.interactions.map((interaction: string, i: number) => (
                            <li key={i}>• {interaction}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Security Considerations */}
          {(prd.architecture as { security_considerations?: string }).security_considerations && (
            <div className="border rounded-lg p-4 mt-4 bg-amber-50/50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800">
              <h4 className="font-medium mb-2 flex items-center gap-2">
                <span className="text-amber-600 dark:text-amber-400">🔒</span> Security Considerations
              </h4>
              <p className="text-sm text-muted-foreground">{(prd.architecture as { security_considerations?: string }).security_considerations}</p>
            </div>
          )}

          {prd.architecture.data_flow && (
            <div className="border rounded-lg p-4 mt-4 bg-muted/30 dark:bg-slate-800/50">
              <h4 className="font-medium mb-2">Data Flow</h4>
              <p className="text-sm text-muted-foreground">{prd.architecture.data_flow}</p>
            </div>
          )}
        </div>
      )}

      {/* Implementation Requirements */}
      {prd.implementation_requirements && prd.implementation_requirements.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Implementation Requirements</h3>
          <div className="space-y-3">
            {prd.implementation_requirements.map((req: { id: string; title: string; description: string; priority: string; dependencies?: string[]; effort_estimate?: string; technical_notes?: string }, index: number) => (
              <div key={index} className={`border rounded-lg p-4 ${getPriorityColorClass(req.priority)}`}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono text-sm">{req.id}</span>
                  <div className="flex gap-2">
                    {req.effort_estimate && (
                      <Badge variant="secondary" className="text-xs">
                        {req.effort_estimate} Effort
                      </Badge>
                    )}
                    <Badge variant="outline" className="bg-white dark:bg-slate-800 dark:border-slate-700">
                      {req.priority} Priority
                    </Badge>
                  </div>
                </div>
                <h4 className="font-medium mb-2">{req.title}</h4>
                <p className="text-sm text-muted-foreground mb-2">{req.description}</p>
                {req.technical_notes && (
                  <div className="bg-blue-50/50 dark:bg-blue-900/20 rounded p-2 mb-2">
                    <span className="text-xs font-medium text-blue-700 dark:text-blue-300">Technical Notes: </span>
                    <span className="text-xs text-muted-foreground">{req.technical_notes}</span>
                  </div>
                )}
                {req.dependencies && req.dependencies.length > 0 && (
                  <div>
                    <span className="text-xs font-medium text-muted-foreground">Dependencies:</span>
                    <div className="flex flex-wrap gap-1 mt-1">
                      {req.dependencies.map((dep: string, i: number) => (
                        <Badge key={i} variant="secondary" className="text-xs">{dep}</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* API Specifications */}
      {(prd as { api_specifications?: Array<{ endpoint: string; method: string; purpose: string; request_body?: string; response?: string }> }).api_specifications &&
        (prd as { api_specifications?: Array<{ endpoint: string; method: string; purpose: string; request_body?: string; response?: string }> }).api_specifications!.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
              <FileText className="h-5 w-5" />
              API Specifications
            </h3>
            <div className="space-y-3">
              {(prd as { api_specifications?: Array<{ endpoint: string; method: string; purpose: string; request_body?: string; response?: string }> }).api_specifications!.map((api, index: number) => (
                <div key={index} className="border rounded-lg p-4 font-mono text-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant={api.method === 'GET' ? 'secondary' : api.method === 'POST' ? 'default' : 'outline'} className="text-xs">
                      {api.method}
                    </Badge>
                    <span className="font-medium">{api.endpoint}</span>
                  </div>
                  <p className="text-xs text-muted-foreground font-sans mb-2">{api.purpose}</p>
                  {api.request_body && (
                    <div className="bg-muted/30 dark:bg-slate-800/50 rounded p-2 mb-1">
                      <span className="text-xs font-sans font-medium">Request: </span>
                      <span className="text-xs">{api.request_body}</span>
                    </div>
                  )}
                  {api.response && (
                    <div className="bg-green-50/50 dark:bg-green-900/20 rounded p-2">
                      <span className="text-xs font-sans font-medium text-green-700 dark:text-green-300">Response: </span>
                      <span className="text-xs">{api.response}</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

      {/* Non-Functional Requirements */}
      {(prd as { non_functional_requirements?: Array<{ category: string; requirement: string; target: string; measurement?: string }> }).non_functional_requirements &&
        (prd as { non_functional_requirements?: Array<{ category: string; requirement: string; target: string; measurement?: string }> }).non_functional_requirements!.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-3">Non-Functional Requirements</h3>
            <div className="grid md:grid-cols-2 gap-3">
              {(prd as { non_functional_requirements?: Array<{ category: string; requirement: string; target: string; measurement?: string }> }).non_functional_requirements!.map((nfr, index: number) => (
                <div key={index} className="border rounded-lg p-4">
                  <Badge variant="outline" className="mb-2 text-xs">{nfr.category}</Badge>
                  <p className="text-sm font-medium mb-1">{nfr.requirement}</p>
                  <p className="text-xs text-green-700 dark:text-green-300">Target: {nfr.target}</p>
                  {nfr.measurement && (
                    <p className="text-xs text-muted-foreground mt-1">Measurement: {nfr.measurement}</p>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

      {/* Testing & Validation */}
      {prd.testing_validation && prd.testing_validation.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Testing & Validation</h3>
          <div className="space-y-3">
            {prd.testing_validation.map((test: { test_type: string; description: string; success_criteria: string; coverage_target?: string }, index: number) => (
              <div key={index} className="border rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-medium">{test.test_type}</h4>
                  {test.coverage_target && (
                    <Badge variant="secondary" className="text-xs">Coverage: {test.coverage_target}</Badge>
                  )}
                </div>
                <p className="text-sm text-muted-foreground mb-2">{test.description}</p>
                <div className="bg-muted/30 dark:bg-slate-800/50 rounded p-2">
                  <span className="text-xs font-medium">Success Criteria:</span>
                  <p className="text-xs text-muted-foreground mt-1">{test.success_criteria}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Technical Success Metrics */}
      {prd.success_metrics && prd.success_metrics.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <Lightbulb className="h-5 w-5" />
            Technical Success Metrics
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {prd.success_metrics.map((metric: { metric: string; target: string; measurement_method: string }, index: number) => (
              <div key={index} className="border rounded-lg p-4 bg-muted/30 dark:bg-slate-800/50">
                <h4 className="font-medium mb-1">{metric.metric}</h4>
                <p className="text-sm font-medium text-green-700 dark:text-green-300 mb-2">{metric.target}</p>
                <p className="text-xs text-muted-foreground">{metric.measurement_method}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default PRDDisplay;
